[tool.black]
line-length = 79
target-version = ['py39']
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.venv
)/
'''

[tool.isort]
profile = 'black'
line_length = 79
lines_after_imports = 2
force_sort_within_sections = 'True'
order_by_type = 'False'
