[tool.black]
line-length = 79
target-version = ['py39']
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | docs
)/
'''

[tool.isort]
profile = 'black'
line_length = 79
lines_after_imports = 2
force_sort_within_sections = 'True'
order_by_type = 'False'
