# Using GitHub CLI in workflows
# https://docs.github.com/en/actions/using-workflows/using-github-cli-in-workflows
name: Compare actions

description: Compare actions' environments and show their diff

inputs:
  token:
    description: 'GitHub token'
    required: true

runs:
  using: composite
  steps:
    - run: gh pr comment $PULL_REQUEST --body "Hi!"
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        PULL_REQUEST: ${{ github.event.pull_request.html_url }}
