name: Lint

on:
  push:
    branches:
      - master
      - 'ci/**'
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort
    - name: isort
      if: always()
      run: |
        isort . --diff --check
    - name: flake8
      if: always()
      run: |
        flake8 .
    - name: black
      if: always()
      run: |
        black . --diff
