name: Check Code Format

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort

    - name: isort
      if: always()
      run: |
        isort . --diff --check

    - name: flake8
      if: always()
      run: |
        flake8 .

    - name: black
      if: always()
      run: |
        black . --diff
