name: Test

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        pl-release: ["stable", "master"]
        torch-release: ["lts", "stable", "nightly"]
    # https://github.com/conda-incubator/setup-miniconda/issues/179
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        miniconda-version: latest
        activate-environment: test
        auto-update-conda: true
    - name: Install PyTorch (stable)
      if: ${{ matrix.torch-release }} == stable
      run: conda install pytorch torchvision cpuonly -c pytorch
    - name: Install PyTorch (lts)
      if: ${{ matrix.torch-release }} == lts
      run: conda install pytorch torchvision cpuonly -c pytorch-lts
    - name: Install PyTorch (nightly)
      if: ${{ matrix.torch-release }} == nightly
      run: conda install pytorch torchvision cpuonly -c pytorch-nightly
    - name: Install dependencies
      run: |
        pip install -r requirements/all.txt
    - name: Run main.py
      run: |
        for i in $(find . -type f -name main.py)
        do
          echo "Testing ${i}"
          python ${i}
        done
