name: Run main scripts

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        pl-release: ["stable", "master"]
        torch-release: ["lts", "stable"]
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        miniconda-version: latest
        activate-environment: test
        auto-update-conda: true
        auto-activate-base: false
    - name: Install dependencies
      run: |
        which python pip conda
        python --version
        pip --version
        pip list
        # conda install pytorch torchvision cpuonly -c pytorch-lts
        # conda install pytorch torchvision cpuonly -c pytorch
        conda install -q pytorch torchvision cpuonly -c pytorch-nightly
        python -c "import torch; print(torch.__version__)"
        conda info -e
        conda list
        python -c "import torch; print(torch.__version__)"
        # pip install -r requirements/all.txt
    # - name: Run main.py
    #   run: |
    #     for i in $(find . -type f -name main.py)
    #     do
    #       echo "Testing ${i}"
    #       python ${i}
    #     done
