name: Run main scripts

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install -r requirements/all.txt -f https://download.pytorch.org/whl/cpu/torch_stable.html
    - name: Run main.py
      run: |
        for i in $(find . -type f -name main.py)
        do
          echo "Testing ${i}"
          python ${i}
        done
