name: Test

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
      - "ci/**"
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        pl-branch: ["release/stable", "master"]
        torch-conda-channel: ["pytorch", "pytorch-lts", "pytorch-nightly"]
    # https://github.com/conda-incubator/setup-miniconda/issues/179
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          miniconda-version: latest
          activate-environment: test
          auto-update-conda: true
      - name: Install dependencies
        run: |
          # Install PyTorch
          conda install -q pytorch torchvision cpuonly -c ${{ matrix.torch-conda-channel }}
          # Install PyTorch Lightning
          pip install -q 'https://github.com/PyTorchLightning/pytorch-lightning/archive/${{ matrix.pl-branch }}.zip'
      - name: Show environment
        run: |
          python --version
          pip list
          conda info
          conda list
      - name: Run main.py
        run: |
          for i in $(find . -type f -name main.py)
          do
            echo "Testing ${i}"
            python ${i}
          done
